[package]
name = "chatpurp-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
chatpurp-contracts = { path = "../chatpurp-contracts" }
dioxus.workspace = true
serde_json.workspace = true
serde.workspace = true
reqwest.workspace = true
web-sys = { version = "=0.3.105", features = ["Window", "Location"] }
